// Mock data for La Santa Cruz - Premium Fashion Management Platform

export const mockProducts = [
  {
    id: "1",
    name: "Vestido Bordado Tradicional",
    brand: "La Santa Cruz",
    category: "Vestidos",
    price: 2850,
    discountPrice: 2280,
    discount: 20,
    image: "/placeholder.svg",
    stock: 12,
    isFavorite: false,
    status: "in-stock" as const,
  },
  {
    id: "2",
    name: "Blusa Artesanal Oaxaqueña",
    brand: "La Santa Cruz",
    category: "Blusas",
    price: 1450,
    discountPrice: null,
    discount: null,
    image: "/placeholder.svg",
    stock: 8,
    isFavorite: true,
    status: "in-stock" as const,
  },
  {
    id: "3",
    name: "Falda Huipil Bordada",
    brand: "La Santa Cruz",
    category: "Faldas",
    price: 1980,
    discountPrice: 1584,
    discount: 20,
    image: "/placeholder.svg",
    stock: 3,
    isFavorite: false,
    status: "low-stock" as const,
  },
  {
    id: "4",
    name: "Rebozo de Seda Natural",
    brand: "La Santa Cruz",
    category: "Accesorios",
    price: 3200,
    discountPrice: null,
    discount: null,
    image: "/placeholder.svg",
    stock: 0,
    isFavorite: false,
    status: "out-of-stock" as const,
  },
  {
    id: "5",
    name: "Camisa Manta Bordada",
    brand: "La Santa Cruz",
    category: "Camisas",
    price: 1250,
    discountPrice: 1000,
    discount: 20,
    image: "/placeholder.svg",
    stock: 15,
    isFavorite: true,
    status: "in-stock" as const,
  },
  {
    id: "6",
    name: "Huaraches Artesanales",
    brand: "La Santa Cruz",
    category: "Calzado",
    price: 890,
    discountPrice: null,
    discount: null,
    image: "/placeholder.svg",
    stock: 22,
    isFavorite: false,
    status: "in-stock" as const,
  },
]

export const mockUsers = [
  {
    id: "1",
    name: "María González",
    email: "maria@lasantacruz.mx",
    role: "admin-global",
    avatar: "/placeholder.svg",
    status: "active" as const,
    lastLogin: "2024-01-15T10:30:00Z",
  },
  {
    id: "2",
    name: "Carlos Hernández",
    email: "carlos@lasantacruz.mx",
    role: "admin-sede",
    avatar: "/placeholder.svg",
    status: "active" as const,
    lastLogin: "2024-01-15T09:15:00Z",
  },
  {
    id: "3",
    name: "Ana Martínez",
    email: "ana@lasantacruz.mx",
    role: "vendedor",
    avatar: "/placeholder.svg",
    status: "active" as const,
    lastLogin: "2024-01-15T08:00:00Z",
  },
  {
    id: "4",
    name: "Pedro López",
    email: "pedro@cliente.com",
    role: "cliente",
    avatar: "/placeholder.svg",
    status: "inactive" as const,
    lastLogin: "2024-01-10T14:20:00Z",
  },
]

export const mockNotifications = [
  {
    id: "1",
    title: "Nuevo pedido recibido",
    message: "Pedido #1234 de María González",
    type: "order" as const,
    read: false,
    createdAt: "2024-01-15T10:30:00Z",
  },
  {
    id: "2",
    title: "Stock bajo",
    message: "Falda Huipil Bordada - Solo quedan 3 unidades",
    type: "warning" as const,
    read: false,
    createdAt: "2024-01-15T09:00:00Z",
  },
  {
    id: "3",
    title: "Producto agotado",
    message: "Rebozo de Seda Natural sin stock",
    type: "error" as const,
    read: true,
    createdAt: "2024-01-14T16:45:00Z",
  },
  {
    id: "4",
    title: "Meta de ventas alcanzada",
    message: "Felicidades! Has alcanzado el 120% de tu meta mensual",
    type: "success" as const,
    read: true,
    createdAt: "2024-01-14T12:00:00Z",
  },
]

export const mockOrders = [
  {
    id: "ORD-001",
    customer: "María González",
    email: "maria@example.com",
    items: 3,
    total: 5280,
    status: "completed" as const,
    date: "2024-01-15T10:30:00Z",
    paymentMethod: "Tarjeta",
  },
  {
    id: "ORD-002",
    customer: "Juan Pérez",
    email: "juan@example.com",
    items: 1,
    total: 1450,
    status: "pending" as const,
    date: "2024-01-15T09:15:00Z",
    paymentMethod: "Efectivo",
  },
  {
    id: "ORD-003",
    customer: "Laura Sánchez",
    email: "laura@example.com",
    items: 2,
    total: 3200,
    status: "processing" as const,
    date: "2024-01-15T08:00:00Z",
    paymentMethod: "Transferencia",
  },
  {
    id: "ORD-004",
    customer: "Roberto Díaz",
    email: "roberto@example.com",
    items: 1,
    total: 890,
    status: "cancelled" as const,
    date: "2024-01-14T16:45:00Z",
    paymentMethod: "Tarjeta",
  },
  {
    id: "ORD-005",
    customer: "Carmen Ruiz",
    email: "carmen@example.com",
    items: 4,
    total: 7500,
    status: "completed" as const,
    date: "2024-01-14T14:20:00Z",
    paymentMethod: "Tarjeta",
  },
]

export const mockMetrics = {
  totalSales: 285400,
  ordersToday: 24,
  averageTicket: 1890,
  conversionRate: 3.2,
  salesGrowth: 12.5,
  ordersGrowth: 8.3,
  ticketGrowth: -2.1,
  conversionGrowth: 0.5,
}

export const mockSalesData = [
  { name: "Lun", ventas: 12400, pedidos: 8 },
  { name: "Mar", ventas: 18200, pedidos: 12 },
  { name: "Mié", ventas: 15800, pedidos: 10 },
  { name: "Jue", ventas: 22100, pedidos: 15 },
  { name: "Vie", ventas: 28500, pedidos: 20 },
  { name: "Sáb", ventas: 35200, pedidos: 25 },
  { name: "Dom", ventas: 19800, pedidos: 14 },
]

export const mockCategoryData = [
  { name: "Vestidos", value: 35, color: "#5FA37A" },
  { name: "Blusas", value: 25, color: "#8FC9CB" },
  { name: "Accesorios", value: 20, color: "#97C1A9" },
  { name: "Calzado", value: 12, color: "#B7CFB7" },
  { name: "Otros", value: 8, color: "#CCE2CB" },
]

export const mockStockAlerts = [
  {
    id: "1",
    product: "Falda Huipil Bordada",
    currentStock: 3,
    minStock: 5,
    severity: "warning" as const,
  },
  {
    id: "2",
    product: "Rebozo de Seda Natural",
    currentStock: 0,
    minStock: 3,
    severity: "critical" as const,
  },
  {
    id: "3",
    product: "Vestido Bordado Tradicional",
    currentStock: 4,
    minStock: 5,
    severity: "warning" as const,
  },
]

export const mockSedes = [
  {
    id: "1",
    name: "La Santa Cruz - Centro",
    address: "Av. Juárez 123, Centro Histórico",
    city: "Oaxaca",
    manager: "Carlos Hernández",
    employees: 8,
    status: "active" as const,
  },
  {
    id: "2",
    name: "La Santa Cruz - Reforma",
    address: "Paseo de la Reforma 456",
    city: "CDMX",
    manager: "Ana Martínez",
    employees: 12,
    status: "active" as const,
  },
  {
    id: "3",
    name: "La Santa Cruz - Polanco",
    address: "Av. Presidente Masaryk 789",
    city: "CDMX",
    manager: "Miguel Torres",
    employees: 6,
    status: "inactive" as const,
  },
]

export const mockActivityFeed = [
  {
    id: "1",
    action: "Venta completada",
    description: "Pedido #1234 - $5,280 MXN",
    user: "Ana Martínez",
    time: "Hace 5 min",
    type: "sale" as const,
  },
  {
    id: "2",
    action: "Producto actualizado",
    description: "Stock actualizado: Vestido Bordado Tradicional",
    user: "Carlos Hernández",
    time: "Hace 15 min",
    type: "update" as const,
  },
  {
    id: "3",
    action: "Nuevo cliente registrado",
    description: "María González se registró",
    user: "Sistema",
    time: "Hace 30 min",
    type: "user" as const,
  },
  {
    id: "4",
    action: "Alerta de stock",
    description: "Rebozo de Seda Natural agotado",
    user: "Sistema",
    time: "Hace 1 hora",
    type: "alert" as const,
  },
]
